# Generated by Django 5.1.7 on 2025-03-25 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoiskapiunofficial_tech_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='actor',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actors', to=settings.AUTH_USER_MODEL, verbose_name='Владелец записи'),
        ),
        migrations.AddField(
            model_name='film',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='films', to=settings.AUTH_USER_MODEL, verbose_name='Владелец записи'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='Владелец записи'),
        ),
    ]
