# Generated by Django 5.1.6 on 2025-02-20 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Укажите здесь имя автора', max_length=100)),
                ('last_name', models.CharField(help_text='Укажите здесь фамилию автора', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, help_text='Укажите здесь дату рождения автора', null=True)),
                ('date_of_death', models.DateField(blank=True, help_text='Укажите здесь дату смерти автора', null=True)),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите здесь жанр книги', max_length=200)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Укажите здесь название книги', max_length=200)),
                ('short_description', models.TextField(help_text='Укажите здесь краткое описание книги', max_length=1000)),
                ('isbn', models.CharField(blank=True, help_text='Укажите здесь ISBN книги', max_length=20, null=True)),
                ('author', models.ForeignKey(blank=True, help_text='Выберите здесь автора книги', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors_books_app.author')),
                ('genre', models.ManyToManyField(help_text='Выберите здесь жанр книги', to='authors_books_app.genre')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ('id',),
            },
        ),
    ]
