# Generated by Django 5.1.6 on 2025-02-24 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors_books_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Укажите здесь дату рождения автора', null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, help_text='Укажите здесь дату смерти автора', null=True, verbose_name='Дата смерти'),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(help_text='Укажите здесь имя автора', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(help_text='Укажите здесь фамилию автора', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Выберите здесь автора книги', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors_books_app.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Выберите здесь жанр книги', to='authors_books_app.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, help_text='Укажите здесь ISBN книги', max_length=20, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='short_description',
            field=models.TextField(help_text='Укажите здесь краткое описание книги', max_length=1000, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Укажите здесь название книги', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Укажите здесь название жанра книги', max_length=200, verbose_name='Название жанра'),
        ),
    ]
