# Generated by Django 5.1.6 on 2025-02-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors_books_app', '0002_alter_author_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(blank=True, help_text='Укажите здесь фамилию автора', max_length=100, null=True, verbose_name='Фамилия'),
        ),
    ]
