# Generated by Django 5.1.6 on 2025-03-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors_books_app', '0006_book_owner_genre_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, help_text='Укажите здесь ISBN книги', max_length=20, null=True, unique=True, verbose_name='ISBN'),
        ),
    ]
